"""Crear Tabla de Maestros

Revision ID: 753bc697d449
Revises: b98503fbfd1a
Create Date: 2026-02-27 19:48:33.559949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753bc697d449'
down_revision = 'b98503fbfd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maestros',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellidos', sa.String(length=50), nullable=True),
    sa.Column('especialidad', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maestros')
    # ### end Alembic commands ###
